apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: NAMESPACE_TO_REPLACE
  name: podcreat-neoload
rules:
- apiGroups: [""]
  resources: ["pods", "services","routes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]