---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-neoload-service
  labels:
    "app": "keptn"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-neoload-service-secrets
  labels:
    "app": "keptn"
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-neoload-service-secrets
  labels:
    "app": "keptn"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-neoload-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-dynatrace-sli-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: NAMESPACE_TO_REPLACE
  name: podcreat-neoload
rules:
- apiGroups: [""]
  resources: ["pods", "services","routes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: podcreat-neoload-binding
  namespace: NAMESPACE_TO_REPLACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podcreat-neoload
subjects:
- apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts:NAMESPACE_TO_REPLACE
  kind: Group