---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neoload-service
  namespace: NAMESPACE_TO_REPLACE
spec:
  selector:
    matchLabels:
      run: neoload-service
  replicas: 1
  template:
    metadata:
      labels:
        run: neoload-service
    spec:
      containers:
        - name: neoload-service
          image: hrexed/keptn_neoload:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: logging-level
              value: DEBUG
          envFrom:
            - configMapRef:
                name: neoload-config
            - secretKeyRef:
                name: neoload
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: neoload-service
  namespace: NAMESPACE_TO_REPLACE
  labels:
    run: neoload-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: neoload-service